name: 'actions-license-check'
description: 'Action to check the repo for (production) dependencies that have an disallowed license'
author: 'tangro'
inputs:
  allowed-licenses:
    description: 'The list of allowed licenses. Use semicolons to separate licenses.'
    required: false
    default: 'MIT; Apache-2.0; ISC; BSD'
  sub-dir:
    description: 'Run check in a sub directory'
    required: false
    default: '.'

runs:
  using: 'node16'
  main: 'dist/index.js'
